/**
 * Shared server runtime resolution for serve-like commands
 */
import { request as httpRequest } from 'node:http'
import { request as httpsRequest } from 'node:https'
import { readFileSync } from 'node:fs'
import type { FastifyInstance } from 'fastify'
import { loadCliConfig } from './config.ts'
import { buildApp } from '../server/app.ts'
import { createConfig, generateToken, type ServerConfig } from '../server/config.ts'
import { initDatabase, closeDatabase } from '../server/db/index.ts'
import { loadOrCreateCertificates, getCertificatePaths } from '../server/tls/certificates.ts'

export interface ResolvedServerRuntime {
  config: ServerConfig;
  openBrowser: boolean;
  verbose: boolean;
  tokenAutoGenerated: boolean;
  certificatePath?: string;
}

export interface StartedServerHandle {
  app: FastifyInstance;
  startedByCommand: boolean;
  close: () => Promise<void>;
}

function getConnectHost (host: string): string {
  if (host === '0.0.0.0') return '127.0.0.1'
  if (host === '::') return 'localhost'
  return host
}

export function getAppUrl (config: ServerConfig, pathname = '/'): string {
  const protocol = config.https ? 'https' : 'http'
  const host = getConnectHost(config.host)
  const url = new URL(`${protocol}://${host}:${config.port}`)
  url.pathname = pathname

  if (config.authToken) {
    url.searchParams.set('token', config.authToken)
  }

  return url.toString()
}

export function getAccessUrl (config: ServerConfig): string {
  return getAppUrl(config, '/')
}

async function healthCheck (config: ServerConfig): Promise<boolean> {
  const host = getConnectHost(config.host)

  return await new Promise((resolve) => {
    const onResponse = (res: { statusCode?: number | undefined; resume: () => void }) => {
      res.resume()
      resolve((res.statusCode ?? 0) >= 200 && (res.statusCode ?? 0) < 300)
    }

    const req = config.https
      ? httpsRequest({
        protocol: 'https:',
        hostname: host,
        port: config.port,
        path: '/api/health',
        method: 'GET',
        timeout: 1000,
        rejectUnauthorized: false,
      }, onResponse)
      : httpRequest({
        protocol: 'http:',
        hostname: host,
        port: config.port,
        path: '/api/health',
        method: 'GET',
        timeout: 1000,
      }, onResponse)

    req.on('timeout', () => {
      req.destroy()
      resolve(false)
    })

    req.on('error', () => {
      resolve(false)
    })

    req.end()
  })
}

/**
 * Check if --auth flag is present and if it has a value.
 * Returns:
 * - undefined: --auth not present
 * - null: --auth present without value (auto-generate)
 * - string: --auth present with value
 */
export function extractAuthArg (args: string[]): string | null | undefined {
  const authIndex = args.findIndex(arg => arg === '--auth')
  if (authIndex === -1) {
    return undefined
  }

  const nextArg = args[authIndex + 1]
  if (!nextArg || nextArg.startsWith('-')) {
    return null
  }

  return nextArg
}

export function stripAuthArg (args: string[], authValue: string | null | undefined): string[] {
  if (authValue === undefined) {
    return args
  }

  const authIndex = args.findIndex(arg => arg === '--auth')
  if (authIndex === -1) {
    return args
  }

  if (authValue === null) {
    return [...args.slice(0, authIndex), ...args.slice(authIndex + 1)]
  }

  return [...args.slice(0, authIndex), ...args.slice(authIndex + 2)]
}

export async function resolveServerRuntime (args: string[], values: {
  port?: string;
  open?: boolean;
  host?: string;
  https?: boolean;
  cert?: string;
  key?: string;
  verbose?: boolean;
}): Promise<ResolvedServerRuntime> {
  const authValue = extractAuthArg(args)
  const cliConfig = loadCliConfig()
  const fileConfig = cliConfig.values

  const host = values.host ?? fileConfig.host ?? 'localhost'
  const port = parseInt(values.port ?? String(fileConfig.port ?? 3847), 10)
  const openBrowser = values.open ?? fileConfig.open ?? true
  const verbose = values.verbose ?? false
  const isNonLocalhost = host !== 'localhost' && host !== '127.0.0.1'

  if (!Number.isInteger(port) || port <= 0) {
    throw new Error('--port must be a positive integer')
  }

  if ((values.cert && !values.key) || (!values.cert && values.key)) {
    throw new Error('--cert and --key must be specified together')
  }

  let authToken: string | undefined
  let tokenAutoGenerated = false

  if (typeof authValue === 'string') {
    authToken = authValue
  } else if (authValue === null) {
    authToken = generateToken()
    tokenAutoGenerated = true
  } else if (fileConfig.authToken) {
    authToken = fileConfig.authToken
  } else if (isNonLocalhost) {
    authToken = generateToken()
    tokenAutoGenerated = true
  }

  const hasCustomCerts = !!(values.cert && values.key)
  const httpsPreference = values.https ?? fileConfig.https
  const enableHttps = hasCustomCerts || (httpsPreference ?? isNonLocalhost)
  let tlsCert: string | undefined
  let tlsKey: string | undefined
  let certificatePath: string | undefined

  if (enableHttps) {
    if (hasCustomCerts) {
      tlsCert = readFileSync(values.cert!, 'utf-8')
      tlsKey = readFileSync(values.key!, 'utf-8')
      certificatePath = values.cert!
    } else {
      const { cert, key } = await loadOrCreateCertificates()
      tlsCert = cert
      tlsKey = key
      certificatePath = getCertificatePaths().certPath
    }
  }

  const config = createConfig({
    port,
    host,
    authToken,
    https: enableHttps,
    tlsCert,
    tlsKey,
  })

  return {
    config,
    openBrowser,
    verbose,
    tokenAutoGenerated,
    certificatePath,
  }
}

export async function ensureServerRunning (runtime: ResolvedServerRuntime): Promise<StartedServerHandle> {
  const running = await healthCheck(runtime.config)

  if (running) {
    initDatabase(runtime.config.dbPath)
    return {
      app: null as unknown as FastifyInstance,
      startedByCommand: false,
      close: async () => {
        closeDatabase()
      },
    }
  }

  initDatabase(runtime.config.dbPath)
  const app = await buildApp(runtime.config, {
    logger: runtime.verbose,
    verbose: runtime.verbose,
  })
  await app.listen({ port: runtime.config.port, host: runtime.config.host })

  return {
    app,
    startedByCommand: true,
    close: async () => {
      await app.close()
      closeDatabase()
    },
  }
}
