/**
 * Serve command - start the review server
 */
import { parseArgs } from 'node:util'
import open from 'open'
import { startServer } from '../../server/index.ts'
import { getAccessUrl, resolveServerRuntime, extractAuthArg, stripAuthArg } from '../server-runtime.ts'

function printHelp () {
  console.log(`
Usage: githuman serve [options]

Start the review server and open web interface.

Options:
  -p, --port <number>    Port to run server on (default: 3847)
  --open                 Auto-open browser (default: true)
  --no-open              Don't auto-open browser
  --host <string>        Host to bind to (default: localhost)
  --https                Force HTTPS (auto-generates self-signed cert if needed)
  --no-https             Disable HTTPS
  --cert <path>          Path to TLS certificate file (PEM format)
  --key <path>           Path to TLS private key file (PEM format)
  --auth [token]         Enable auth (auto-generates token if no value given)
  -v, --verbose          Enable verbose logging (full pino-pretty output)
  -h, --help             Show this help message

Config file:
  - .githuman/config.json can provide default host, port, https, open, and authToken
  - CLI flags override config file values

HTTPS:
  - localhost (default): HTTP unless --https or config enables HTTPS
  - non-localhost host: HTTPS auto-enabled with a self-signed certificate unless --no-https is used
  - --cert/--key: Use custom certificates (both required together)
  - Auto-generated certificates stored in ~/.githuman/cert.pem and ~/.githuman/key.pem

Authentication:
  - localhost (default): No auth required unless configured
  - non-localhost host: Auth auto-enabled with generated token
  - --auth: Explicitly enable auth (auto-generate or provide your own 32+ char token)
`)
}

export async function serveCommand (args: string[]) {
  const authValue = extractAuthArg(args)
  const filteredArgs = stripAuthArg(args, authValue)

  const { values } = parseArgs({
    args: filteredArgs,
    allowNegative: true,
    options: {
      port: { type: 'string', short: 'p' },
      open: { type: 'boolean' },
      host: { type: 'string' },
      https: { type: 'boolean' },
      cert: { type: 'string' },
      key: { type: 'string' },
      verbose: { type: 'boolean', short: 'v' },
      help: { type: 'boolean', short: 'h' },
    },
  })

  if (values.help) {
    printHelp()
    return
  }

  const runtime = await resolveServerRuntime(args, {
    port: values.port,
    open: values.open,
    host: values.host,
    https: values.https,
    cert: values.cert,
    key: values.key,
    verbose: values.verbose,
  })

  await startServer(runtime.config, {
    verbose: runtime.verbose,
    tokenAutoGenerated: runtime.tokenAutoGenerated,
    certificatePath: runtime.certificatePath,
  })

  if (runtime.openBrowser) {
    await open(getAccessUrl(runtime.config))
  }
}
