/**
 * Serve command - start the review server
 */
import { parseArgs } from 'node:util'
import open from 'open'
import { startServer, createConfig, generateToken } from '../../server/index.ts'

function printHelp () {
  console.log(`
Usage: githuman serve [options]

Start the review server and open web interface.

Options:
  -p, --port <number>    Port to run server on (default: 3847)
  --no-open              Don't auto-open browser
  --host <string>        Host to bind to (default: localhost)
  --auth [token]         Enable auth (auto-generates token if no value given)
  -v, --verbose          Enable verbose logging (full pino-pretty output)
  -h, --help             Show this help message

Authentication:
  - localhost (default): No auth required - safe for local development
  - --host specified: Auth auto-enabled with generated token
  - --auth: Explicitly enable auth (auto-generate or provide your own 32+ char token)
`)
}

/**
 * Check if --auth flag is present and if it has a value.
 * Returns:
 * - undefined: --auth not present
 * - null: --auth present without value (auto-generate)
 * - string: --auth present with value
 */
function extractAuthArg (args: string[]): string | null | undefined {
  const authIndex = args.findIndex(arg => arg === '--auth')
  if (authIndex === -1) {
    return undefined // --auth not present
  }

  const nextArg = args[authIndex + 1]
  if (!nextArg || nextArg.startsWith('-')) {
    return null // --auth present but no value
  }

  return nextArg // --auth with value
}

export async function serveCommand (args: string[]) {
  // Pre-process --auth to handle optional value
  const authValue = extractAuthArg(args)

  // Remove --auth and its value from args for parseArgs (if present with value)
  let filteredArgs = args
  if (authValue !== undefined) {
    const authIndex = args.findIndex(arg => arg === '--auth')
    if (authValue === null) {
      // Just --auth without value, remove only --auth
      filteredArgs = [...args.slice(0, authIndex), ...args.slice(authIndex + 1)]
    } else {
      // --auth with value, remove both
      filteredArgs = [...args.slice(0, authIndex), ...args.slice(authIndex + 2)]
    }
  }

  const { values } = parseArgs({
    args: filteredArgs,
    allowNegative: true,
    options: {
      port: { type: 'string', short: 'p', default: '3847' },
      open: { type: 'boolean', default: true },
      host: { type: 'string', default: 'localhost' },
      verbose: { type: 'boolean', short: 'v', default: false },
      help: { type: 'boolean', short: 'h' },
    },
  })

  if (values.help) {
    printHelp()
    process.exit(0)
  }

  const host = values.host!
  const isNonLocalhost = host !== 'localhost' && host !== '127.0.0.1'

  // Determine auth token:
  // - If --auth was used with a value, use that value
  // - If --auth was used without value, auto-generate
  // - If --host is specified (non-localhost), auto-generate
  // - Otherwise (localhost, no --auth), no auth needed
  let authToken: string | undefined
  let tokenAutoGenerated = false
  if (typeof authValue === 'string') {
    // --auth <token> provided
    authToken = authValue
  } else if (authValue === null || isNonLocalhost) {
    // --auth without value OR non-localhost host → auto-generate
    authToken = generateToken()
    tokenAutoGenerated = true
  }
  // else: localhost without --auth → no auth (authToken remains undefined → null in config)

  let config
  try {
    config = createConfig({
      port: parseInt(values.port!, 10),
      host,
      authToken,
    })
  } catch (error) {
    if (error instanceof Error && error.message.includes('Auth token')) {
      console.error(`Error: ${error.message}`)
      process.exit(1)
    }
    throw error
  }

  // Start the server
  await startServer(config, { verbose: values.verbose, tokenAutoGenerated })

  // Open browser if requested
  if (values.open) {
    const url = `http://${config.host}:${config.port}`
    await open(url)
  }
}
